### PR TITLE
next gen 2

### PR DESCRIPTION
**Pull request by Mertash**
next gen Search_for_Categories

### CODE REVIEW

**Comment by Mertash** [comment]
Give me admin access please

**Comment by milkaalinka** [comment]
> Give me admin access please

idk how, I was searching through all the settings, but there is not sth that you need((

**Comment by milkaalinka** [comment]
> Give me admin access please

moreover, why are you still not a collaborator? Loot at screenshot. Invitations for 3 of you are pending... Why??
image

**Comment by Mertash** [comment]
update yours Git and test please

**Comment by milkaalinka** [comment]
good)

**Pull request merged**
